import { Check, Clipboard, ExternalLink, Globe2, Sparkles } from "lucide-react";
import type { DashboardDocument } from "../types";

type Props = {
  activeDocument?: DashboardDocument;
  copied: boolean;
  code: string;
  demoUrl: string;
  published: boolean;
  onCopy: () => void;
  onPublish: () => void;
};

export function WidgetPage({ activeDocument, copied, code, demoUrl, published, onCopy, onPublish }: Props) {
  return <div><p className="text-sm font-medium text-[#73806e]">Meet customers where they are</p><h1 className="mt-1 text-3xl font-semibold tracking-[-.06em]">Website widget</h1><p className="mt-2 text-sm text-[#7d877c]">Copy one small snippet to add your selected knowledge source to any website.</p>
    <div className="mt-6 grid gap-5 xl:grid-cols-[.75fr_1.25fr]"><section className="rounded-2xl border border-[#e0e6dc] bg-white p-5"><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#eaf7de] text-[#629238]"><Sparkles size={18} /></span><div><h2 className="font-semibold">Embed your bot</h2><p className="mt-1 text-xs text-[#889287]">Publish first, then paste the snippet into any website.</p></div></div><div className={`mt-5 flex items-center justify-between rounded-xl p-3 ${published ? "bg-[#edf8e5] text-[#588536]" : "bg-[#fff6e6] text-[#8c682c]"}`}><span className="flex items-center gap-2 text-xs font-bold"><Globe2 size={15} />{published ? "Published for customers" : "Private draft"}</span><button className="rounded-lg bg-white px-3 py-1.5 text-xs font-bold shadow-sm transition hover:-translate-y-px" onClick={onPublish} type="button">{published ? "Unpublish" : "Publish widget"}</button></div><pre className="mt-4 overflow-x-auto rounded-xl bg-[#1e2820] p-4 text-xs leading-6 text-[#d9fb97]"><code>{code}</code></pre><div className="mt-4 flex flex-wrap gap-2"><button className="inline-flex items-center gap-2 rounded-xl bg-[#202823] px-4 py-2.5 text-sm font-bold text-white transition hover:-translate-y-px disabled:opacity-50" disabled={!published} onClick={onCopy} type="button">{copied ? <Check size={16} /> : <Clipboard size={16} />}{copied ? "Copied" : "Copy embed code"}</button>{published && <a className="inline-flex items-center gap-2 rounded-xl border border-[#d6e1d0] px-4 py-2.5 text-sm font-bold text-[#5b7154] transition hover:bg-[#f4f8ef]" href={demoUrl} rel="noreferrer" target="_blank"><ExternalLink size={15} />Open test site</a>}</div><div className="mt-5 rounded-xl bg-[#f1f7ec] p-3 text-xs font-bold text-[#688a47]"><i className="mr-2 inline-block h-2 w-2 rounded-full bg-[#72a648]" />Uses {activeDocument?.name ?? "your selected source"}</div></section>
      <section className="overflow-hidden rounded-2xl border border-[#dce6d6] bg-[#edf4e9] p-3"><div className="flex items-center justify-between px-2 pb-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#79934f]">Interactive preview</p><p className="mt-1 text-xs text-[#71806e]">A real web page with a launcher and compact mobile chat.</p></div><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-bold text-[#648c3f]">{published ? "Live test" : "Draft"}</span></div>{published ? <iframe className="h-[min(590px,72dvh)] min-h-[420px] w-full rounded-[18px] border border-[#d6e3d1] bg-white shadow-sm" src={demoUrl} title="Helpwise widget test site" /> : <div className="grid h-[420px] place-items-center rounded-[18px] border border-dashed border-[#bfd1b4] bg-white/70 p-8 text-center"><div><Globe2 className="mx-auto text-[#7da35d]" size={28} /><p className="mt-3 font-semibold">Publish when you are ready to test</p><p className="mt-2 max-w-xs text-xs leading-5 text-[#758075]">Your knowledge stays private until you explicitly publish this bot.</p></div></div>}</section></div>
  </div>;
}
